version: "3.7"
services:
  client:
    build:
      context: ./client
    container_name: "riffstop-client"
    volumes:
      - ./client/src/:/app/src
      - ./:/app/
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
      - "1234:1234"
      - "8080:8080"
    tty: true
  functions:
    build:
      context: ./functions
    container_name: "riffstop-functions"
    volumes:
      - ./functions/src/:/app/src
      - ./:/app/
    ports:
      - "9000:9000"
    tty: true
  database:
    container_name: "riffstop-database"
    build: ./database
    env_file:
      - ./secrets.env
    environment:
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - database-data:/var/lib/postgresql/data/
      - ./database/:/app/
    ports:
      - "5432:5432"

volumes:
  database-data:
